apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}

    scrape_configs:
      - job_name: auth-service
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - auth-service:{{ .Values.auth.port }}

      - job_name: task-service
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - task-service:{{ .Values.task.port }}
